"""Small, process-local rolling API snapshot for the administrator console."""
from __future__ import annotations

from collections import deque
from datetime import datetime, timedelta, timezone
from math import ceil
from statistics import mean
from threading import Lock
from time import monotonic
from functools import wraps

_samples: deque[tuple[float, str, str, int, float, str]] = deque(maxlen=5000)
_daily_counts: dict[str, int] = {}
_minute_counts: dict[int, int] = {}
# Per-minute latency/error aggregate for the admin trend charts (24 h):
# minute -> [requests, business_requests, errors_5xx, total_ms, max_ms, histogram]
_LATENCY_BOUNDS_MS = (5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000)
_STATS_RETENTION_MINUTES = 24 * 60
_minute_stats: dict[int, list] = {}
_last_pruned_minute = 0
_lock = Lock()
_tts_stages: deque[tuple[float, str, float]] = deque(maxlen=2000)


def record_tts_stage(name: str, milliseconds: float) -> None:
    with _lock:
        _tts_stages.append((monotonic(), name, milliseconds))


def timed_tts_stage(name: str):
    def decorate(function):
        @wraps(function)
        def timed(*args, **kwargs):
            start = monotonic()
            try:
                return function(*args, **kwargs)
            finally:
                record_tts_stage(name, (monotonic() - start) * 1000)
        return timed
    return decorate

# Read-only status traffic is generated by the UI's background polling. Keep
# latency/error samples for diagnostics, but exclude it from daily usage counts.
_STATUS_ROUTES = frozenset({
    "/api/health",
    "/api/config/client-logs",
    "/api/v1/admin/overview",
    "/api/v1/admin/performance",
    "/api/v1/admin/task-metrics",
    "/api/v1/admin/tasks",
    "/api/v1/admin/gpu-scheduler/status",
    "/api/v1/admin/metrics/history",
    "/api/v1/admin/analytics/throughput",
    "/api/v1/admin/analytics/api",
    "/api/v1/admin/events/stats",
    "/api/v1/tasks",
    "/api/v1/tasks/{task_id}",
    "/api/v1/tasks/stream",
})


def record_api_request(route: str, status: int, duration_ms: float, method: str = "GET") -> None:
    global _last_pruned_minute
    now = datetime.now(timezone.utc)
    local_day = datetime.now().astimezone().date().isoformat()
    minute = int(now.timestamp() // 60)
    business = method.upper() != "GET" or route not in _STATUS_ROUTES
    with _lock:
        _samples.append((monotonic(), method, route, status, duration_ms, now.isoformat()))
        if business:
            _daily_counts[local_day] = _daily_counts.get(local_day, 0) + 1
            _minute_counts[minute] = _minute_counts.get(minute, 0) + 1
        stats = _minute_stats.get(minute)
        if stats is None:
            stats = _minute_stats[minute] = [0, 0, 0, 0.0, 0.0, [0] * (len(_LATENCY_BOUNDS_MS) + 1)]
        stats[0] += 1
        stats[1] += int(business)
        stats[2] += int(status >= 500)
        stats[3] += duration_ms
        stats[4] = max(stats[4], duration_ms)
        stats[5][next((i for i, bound in enumerate(_LATENCY_BOUNDS_MS) if duration_ms <= bound), len(_LATENCY_BOUNDS_MS))] += 1
        if minute == _last_pruned_minute:
            return
        _last_pruned_minute = minute
        cutoff_minute = minute - 3 * 24 * 60
        for bucket in tuple(_minute_counts):
            if bucket < cutoff_minute:
                del _minute_counts[bucket]
        for bucket in tuple(_minute_stats):
            if bucket < minute - _STATS_RETENTION_MINUTES:
                del _minute_stats[bucket]
        for day in tuple(_daily_counts):
            if day != local_day:
                del _daily_counts[day]


def api_requests_today(tz_offset_minutes: int | None = None) -> int:
    """Return requests since midnight, in the process or requested local timezone.

    The per-minute aggregate supports the dashboard's timezone and survives the
    rolling sample buffer limit. Read-only status probes are excluded. Counts
    intentionally reset when the process restarts.
    """
    if tz_offset_minutes is None:
        local_day = datetime.now().astimezone().date().isoformat()
        with _lock:
            return _daily_counts.get(local_day, 0)

    offset = timedelta(minutes=max(-840, min(int(tz_offset_minutes), 840)))
    now = datetime.now(timezone.utc)
    local_start = (now - offset).replace(hour=0, minute=0, second=0, microsecond=0) + offset
    start_minute = int(local_start.timestamp() // 60)
    current_minute = int(now.timestamp() // 60)
    with _lock:
        return sum(count for minute, count in _minute_counts.items() if start_minute <= minute <= current_minute)


def api_snapshot(window_seconds: int = 300) -> dict:
    cutoff = monotonic() - window_seconds
    with _lock:
        recent = [row for row in _samples if row[0] >= cutoff]
        stages = [row for row in _tts_stages if row[0] >= cutoff]
    durations = sorted(row[4] for row in recent)
    failures = sum(1 for row in recent if row[3] >= 500)
    by_route: dict[str, list[tuple[int, float]]] = {}
    for _, _, route, status, duration, _ in recent:
        by_route.setdefault(route, []).append((status, duration))
    return {
        'tts_stages': [
            {'stage': name, 'count': len(values), 'p95_ms': round(sorted(values)[ceil(len(values) * .95) - 1], 1)}
            for name in sorted({row[1] for row in stages})
            for values in [[row[2] for row in stages if row[1] == name]]
        ],
        "window_seconds": window_seconds,
        "request_count": len(recent),
        "server_error_count": failures,
        "error_rate": round(failures / len(recent), 4) if recent else 0,
        "average_ms": round(mean(durations), 1) if durations else None,
        "p95_ms": round(durations[min(len(durations) - 1, ceil(len(durations) * .95) - 1)], 1) if durations else None,
        "status_counts": {
            str(code): sum(1 for row in recent if row[3] == code)
            for code in sorted({row[3] for row in recent})
        },
        "endpoints": [
            {"route": route, "requests": len(rows), "server_errors": sum(1 for status, _ in rows if status >= 500),
             "error_rate": round(sum(1 for status, _ in rows if status >= 500) / len(rows), 4),
             "average_ms": round(mean(duration for _, duration in rows), 1),
             "p95_ms": round(sorted(duration for _, duration in rows)[min(len(rows) - 1, ceil(len(rows) * .95) - 1)], 1)}
            for route, rows in sorted(by_route.items(), key=lambda item: len(item[1]), reverse=True)[:8]
        ],
        "recent_errors": [
            {"time": timestamp, "method": method, "route": route, "status": status}
            for _, method, route, status, _, timestamp in recent if status >= 500
        ][-50:],
        "scope": "当前 API 进程近五分钟；重启后重新计数",
    }


def _histogram_p95(histogram: list[int], total: int, max_ms: float) -> float | None:
    if not total:
        return None
    threshold = ceil(total * .95)
    running = 0
    for index, count in enumerate(histogram):
        running += count
        if running >= threshold:
            return float(_LATENCY_BOUNDS_MS[index]) if index < len(_LATENCY_BOUNDS_MS) else round(max_ms, 1)
    return round(max_ms, 1)


def api_timeseries(minutes: int = 60) -> dict:
    """Bucketed request/error/latency series for the admin trend charts.

    Process-local like the other API aggregates: it covers at most the last
    24 hours and restarts empty with the API process. P95 is approximated
    from a fixed latency histogram (the upper bound of the P95 bucket).
    """
    minutes = max(5, min(int(minutes), _STATS_RETENTION_MINUTES))
    step = 1 if minutes <= 120 else 5 if minutes <= 360 else 15
    current = int(datetime.now(timezone.utc).timestamp() // 60)
    first = (current - minutes + 1) // step * step
    with _lock:
        stats = {minute: (row[0], row[1], row[2], row[3], row[4], list(row[5]))
                 for minute, row in _minute_stats.items() if minute >= first}
    points = []
    for start in range(first, current + 1, step):
        requests = business = errors = 0
        total_ms = max_ms = 0.0
        histogram = [0] * (len(_LATENCY_BOUNDS_MS) + 1)
        for minute in range(start, start + step):
            row = stats.get(minute)
            if row is None:
                continue
            requests += row[0]; business += row[1]; errors += row[2]; total_ms += row[3]
            max_ms = max(max_ms, row[4])
            histogram = [a + b for a, b in zip(histogram, row[5])]
        points.append({
            "time": datetime.fromtimestamp(start * 60, timezone.utc).isoformat(),
            "requests": requests, "business_requests": business, "errors": errors,
            "rps": round(requests / (step * 60), 3),
            "average_ms": round(total_ms / requests, 1) if requests else None,
            "p95_ms": _histogram_p95(histogram, requests, max_ms),
        })
    return {"minutes": minutes, "step_minutes": step, "points": points,
            "scope": "当前 API 进程；最长 24 小时；重启后重新计数；P95 为分桶近似"}
