"""Small, process-local rolling API snapshot for the administrator console."""
from __future__ import annotations

from collections import deque
from datetime import datetime, timedelta, timezone
from math import ceil
from statistics import mean
from threading import Lock
from time import monotonic
from functools import wraps

_samples: deque[tuple[float, str, str, int, float, str]] = deque(maxlen=5000)
_daily_counts: dict[str, int] = {}
_minute_counts: dict[int, int] = {}
_lock = Lock()
_tts_stages: deque[tuple[float, str, float]] = deque(maxlen=2000)


def record_tts_stage(name: str, milliseconds: float) -> None:
    with _lock:
        _tts_stages.append((monotonic(), name, milliseconds))


def timed_tts_stage(name: str):
    def decorate(function):
        @wraps(function)
        def timed(*args, **kwargs):
            start = monotonic()
            try:
                return function(*args, **kwargs)
            finally:
                record_tts_stage(name, (monotonic() - start) * 1000)
        return timed
    return decorate

# Read-only status traffic is generated by the UI's background polling. Keep
# latency/error samples for diagnostics, but exclude it from daily usage counts.
_STATUS_ROUTES = frozenset({
    "/api/health",
    "/api/config/client-logs",
    "/api/v1/admin/overview",
    "/api/v1/admin/performance",
    "/api/v1/admin/task-metrics",
    "/api/v1/admin/tasks",
    "/api/v1/admin/gpu-scheduler/status",
    "/api/v1/tasks",
    "/api/v1/tasks/{task_id}",
    "/api/v1/tasks/stream",
})


def record_api_request(route: str, status: int, duration_ms: float, method: str = "GET") -> None:
    now = datetime.now(timezone.utc)
    local_day = datetime.now().astimezone().date().isoformat()
    minute = int(now.timestamp() // 60)
    with _lock:
        _samples.append((monotonic(), method, route, status, duration_ms, now.isoformat()))
        if method.upper() != "GET" or route not in _STATUS_ROUTES:
            _daily_counts[local_day] = _daily_counts.get(local_day, 0) + 1
            _minute_counts[minute] = _minute_counts.get(minute, 0) + 1
        cutoff_minute = minute - 3 * 24 * 60
        for bucket in tuple(_minute_counts):
            if bucket < cutoff_minute:
                del _minute_counts[bucket]
        for day in tuple(_daily_counts):
            if day != local_day:
                del _daily_counts[day]


def api_requests_today(tz_offset_minutes: int | None = None) -> int:
    """Return requests since midnight, in the process or requested local timezone.

    The per-minute aggregate supports the dashboard's timezone and survives the
    rolling sample buffer limit. Read-only status probes are excluded. Counts
    intentionally reset when the process restarts.
    """
    if tz_offset_minutes is None:
        local_day = datetime.now().astimezone().date().isoformat()
        with _lock:
            return _daily_counts.get(local_day, 0)

    offset = timedelta(minutes=max(-840, min(int(tz_offset_minutes), 840)))
    now = datetime.now(timezone.utc)
    local_start = (now - offset).replace(hour=0, minute=0, second=0, microsecond=0) + offset
    start_minute = int(local_start.timestamp() // 60)
    current_minute = int(now.timestamp() // 60)
    with _lock:
        return sum(count for minute, count in _minute_counts.items() if start_minute <= minute <= current_minute)


def api_snapshot(window_seconds: int = 300) -> dict:
    cutoff = monotonic() - window_seconds
    with _lock:
        recent = [row for row in _samples if row[0] >= cutoff]
        stages = [row for row in _tts_stages if row[0] >= cutoff]
    durations = sorted(row[4] for row in recent)
    failures = sum(1 for row in recent if row[3] >= 500)
    by_route: dict[str, list[tuple[int, float]]] = {}
    for _, _, route, status, duration, _ in recent:
        by_route.setdefault(route, []).append((status, duration))
    return {
        'tts_stages': [
            {'stage': name, 'count': len(values), 'p95_ms': round(sorted(values)[ceil(len(values) * .95) - 1], 1)}
            for name in sorted({row[1] for row in stages})
            for values in [[row[2] for row in stages if row[1] == name]]
        ],
        "window_seconds": window_seconds,
        "request_count": len(recent),
        "server_error_count": failures,
        "error_rate": round(failures / len(recent), 4) if recent else 0,
        "average_ms": round(mean(durations), 1) if durations else None,
        "p95_ms": round(durations[min(len(durations) - 1, ceil(len(durations) * .95) - 1)], 1) if durations else None,
        "status_counts": {
            str(code): sum(1 for row in recent if row[3] == code)
            for code in sorted({row[3] for row in recent})
        },
        "endpoints": [
            {"route": route, "requests": len(rows), "server_errors": sum(1 for status, _ in rows if status >= 500),
             "error_rate": round(sum(1 for status, _ in rows if status >= 500) / len(rows), 4),
             "average_ms": round(mean(duration for _, duration in rows), 1),
             "p95_ms": round(sorted(duration for _, duration in rows)[min(len(rows) - 1, ceil(len(rows) * .95) - 1)], 1)}
            for route, rows in sorted(by_route.items(), key=lambda item: len(item[1]), reverse=True)[:8]
        ],
        "recent_errors": [
            {"time": timestamp, "method": method, "route": route, "status": status}
            for _, method, route, status, _, timestamp in recent if status >= 500
        ][-50:],
        "scope": "当前 API 进程近五分钟；重启后重新计数",
    }
