"""Book-splitting endpoints (module: 分册, the split half of 排版与分册).

``POST /api/book/analyze`` previews the repaired chapter structure (chapters +
per-chapter filenames, no files written). ``POST /api/book/split`` writes files to the
workspace's ``02_split_text/`` — either ONE file per repaired chapter
(``smart=true``: re-runs the deterministic repair, byte-identical to
``/smart-split``) or a single ``<base> 全书.txt`` (``whole_book=true``, the
zero-chapter fallback); plain original-structure splitting has been removed.
``POST /api/book/smart-split`` (智能识别) mechanically repairs the chapter
structure and writes renumbered ``第 NNN 章 标题.txt`` files into the same
directory, always reporting every inferred action. Both honour the "no chapters
-> stop, never force-split" invariant — only an explicit ``whole_book`` request
bypasses it.
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from ..core.paths import get_layout
from ..engines import book as B
from . import _common

router = APIRouter(prefix="/api/book", tags=["book"])


class AnalyzeRequest(BaseModel):
    path: str


class SplitRequest(BaseModel):
    path: str
    base: str | None = None  # override the base (file) name
    whole_book: bool = False  # write the entire text as one ``<base> 全书.txt``
    smart: bool = False  # split by the SMART-REPAIRED structure (智能识别结果)


class SmartSplitRequest(BaseModel):
    path: str


def _prepare(path: str) -> dict:
    text, enc, src = _common.read_decoded_file(path)
    analysis = B.analyze_text(text)
    chapters = analysis["chapters"]
    base = B.base_name(src.name)
    return {
        "text": text,
        "analysis": analysis,
        "encoding": enc,
        "src": src,
        "chapters": chapters,
        "base": base,
        "filenames": B.make_chapter_filenames(base, chapters),
    }


def _chapters_payload(chapters) -> list[dict]:
    return [
        {
            "seq": c["seq"],
            "num": c.get("final_num", c.get("num")),
            "numStr": str(c.get("final_num")) if c.get("final_num") is not None else c["numStr"],
            "title": c["title"],
            "chars": c["chars"],
        }
        for c in chapters
    ]


def _display_chapters(chapters) -> list[dict]:
    """Return the chapter shape used by the analysis page.

    Smart repair keeps the original ``num``/``numStr`` for its report and adds
    ``final_num``.  The preview must show the same final numbering as the
    splitter, otherwise the page can show more chapters than the files that
    will actually be written.
    """
    out = []
    for i, chapter in enumerate(chapters, 1):
        c = dict(chapter)
        c["seq"] = i
        if c.get("final_num") is not None:
            c["num"] = c["final_num"]
            c["numStr"] = str(c["final_num"])
        out.append(c)
    return out


def _clear_generated_split_files(split_dir) -> None:
    """Remove only files previously generated by the book splitter.

    Re-running after title/recognition changes used to leave the old set next
    to the new set.  That made a single chapter appear twice in the output
    directory.  Unrelated files and subdirectories are deliberately left
    untouched.
    """
    import re

    legacy = re.compile(r" 分册\d+ 第\d+章\.txt$")
    for path in split_dir.iterdir():
        if not path.is_file():
            continue
        name = path.name
        generated = (
            (name.startswith("第 ") and name.endswith(".txt"))
            or bool(legacy.search(name))
            or name.endswith(" 全书.txt")
        )
        if generated:
            path.unlink()


@router.post("/analyze")
def analyze(req: AnalyzeRequest) -> dict:
    prep = _prepare(req.path)
    raw_chapters = prep["chapters"]
    raw_sequence = B.check_chapter_sequence(raw_chapters)
    chapters = raw_chapters
    filenames = prep["filenames"]
    repair_status = None
    if raw_chapters:
        repair = B.smart_repair(prep["text"], raw_chapters)
        if repair["status"] != "error":
            chapters = _display_chapters(repair["chapters"])
            filenames = B.make_smart_filenames(repair["chapters"])
            repair_status = repair["status"]
    result = {
        "source": str(prep["src"]),
        "encoding": prep["encoding"],
        "base": prep["base"],
        "total_chars": prep["analysis"]["totalChars"],
        "chapters": _chapters_payload(chapters),
        "chapter_count": len(chapters),
        "filenames": filenames,
        "expected_format": B.EXPECTED_CHAPTER_FORMAT,
        "sequence": B.check_chapter_sequence(chapters),
        "raw_chapter_count": len(raw_chapters),
        "raw_sequence": raw_sequence,
        "repair_status": repair_status,
        "error": None,
    }
    if not chapters:
        result["error"] = (
            f"未检测到章节（系统识别的格式：{B.EXPECTED_CHAPTER_FORMAT}）。"
            "可「不处理，按整本继续」（整本输出为单个文件），或重新上传原文。"
        )
    return result


@router.post("/split")
def split(req: SplitRequest) -> dict:
    _common.require_workspace()
    prep = _prepare(req.path)
    chapters, analysis = prep["chapters"], prep["analysis"]

    base = (req.base or prep["base"]).strip() or prep["base"]
    layout = get_layout()

    if req.whole_book:
        # Explicit opt-in: write the whole text as a single file (no chapters
        # detected, user chose to continue) — the parse stage chunks it.
        name = B.make_whole_book_filename(base)
        data = prep["text"].encode("utf-8")
        _clear_generated_split_files(layout.split_text)
        out_path = layout.split_text / name
        # Write raw bytes (no newline translation) so the file reproduces the
        # source's line endings exactly — Path.write_text would turn \n into
        # \r\n on Windows and corrupt the round-trip guarantee.
        out_path.write_bytes(data)
        written = [{"name": name, "path": str(out_path), "chars": analysis["totalChars"]}]
        final_chapters = []
    elif not req.smart:
        # 普通「按原识别结构分册」已从 UI 与 API 移除：分册只按智能识别结果
        # （smart=true）或零章节整本（whole_book=true）。
        raise HTTPException(
            400, "分册须按智能识别结果（smart=true）或整本（whole_book=true）进行。"
        )
    else:
        # 按智能识别结果分册：重跑确定性修复（同输入 → 同结果），写出与
        # /smart-split 完全相同的「第 NNN 章 标题.txt」文件——不产生第二套
        # 命名，02_split_text/ 里只有一套章节文件。
        if not chapters:
            raise HTTPException(
                400, "未检测到章节，无法分册。请先在提示条中选择「不处理，按整本继续」或重新上传原文。"
            )
        repair = B.smart_repair(prep["text"], chapters)
        if repair["status"] == "error":
            raise HTTPException(400, repair.get("error") or "智能识别失败，请检查原文。")
        chapters = repair["chapters"]
        filenames = B.make_smart_filenames(chapters)
        _clear_generated_split_files(layout.split_text)
        written = []
        for ch, fname in zip(chapters, filenames):
            data = B.chapter_content(analysis, ch).encode("utf-8")
            out_path = layout.split_text / fname
            out_path.write_bytes(data)
            written.append({"name": fname, "path": str(out_path), "chars": ch["chars"]})
        final_chapters = _chapters_payload(_display_chapters(chapters))

    return {
        "output_dir": str(layout.split_text),
        "file_count": len(written),
        "files": written,
        "chapters": final_chapters,
    }


@router.post("/smart-split")
def smart_split(req: SmartSplitRequest) -> dict:
    """智能识别：mechanically repair the chapter structure (renumber 1..N in
    physical order, split abnormally long chapters, drop exact-duplicate
    chapters) and write one file per repaired chapter as ``第 NNN 章 标题.txt``
    into ``02_split_text/``. Always produces output when chapters exist —
    every inferred action is reported with a confidence level. Never rewrites
    file content; previously generated split files are cleared first."""
    _common.require_workspace()
    prep = _prepare(req.path)
    chapters, analysis = prep["chapters"], prep["analysis"]
    if not chapters:
        raise HTTPException(
            400, "未检测到章节，无法智能识别。请先排版并确认系统识别到章节，或重新上传原文。"
        )

    repair = B.smart_repair(prep["text"], chapters)
    if repair["status"] == "error":
        raise HTTPException(400, repair.get("error") or "智能识别失败，请检查原文。")

    layout = get_layout()
    filenames = B.make_smart_filenames(repair["chapters"])
    _clear_generated_split_files(layout.split_text)
    written = []
    for ch, fname in zip(repair["chapters"], filenames):
        data = B.chapter_content(analysis, ch).encode("utf-8")
        out_path = layout.split_text / fname
        out_path.write_bytes(data)
        written.append({"name": fname, "path": str(out_path), "chars": ch["chars"]})

    result: dict = {
        "status": repair["status"],
        "output_dir": str(layout.split_text),
        "file_count": len(written),
        "files": written,
        "chapters": [
            {
                "seq": c["seq"],
                "orig_num": c["repair"]["orig_num"],
                "orig_numStr": c["repair"]["orig_numStr"],
                "final_num": c["final_num"],
                "title": c["title"],
                "chars": c["chars"],
                "actions": c["repair"]["actions"],
                "confidence": c["repair"]["confidence"],
            }
            for c in repair["chapters"]
        ],
        "report": repair["report"],
        "baseline_chars": repair["baseline_chars"],
        "original_count": repair["original_count"],
        "expected_format": B.EXPECTED_CHAPTER_FORMAT,
    }
    return result
